
Q.  Given:

public class Concert {
static class PowerOutage extends Exception {}
static class Thunderstorm extends Exception {}
public static void main(String[] args) {
try {
new Concert().listen();
System.out.println("a");
} catch(PowerOutage | Thunderstorm e) {
e = new PowerOutage();
System.out.println("b");
} finally { System.out.println("c"); }
}
public void listen() throws PowerOutage, Thunderstorm{ }
}

What will this code print?
1). a
2). ab
3). ac
4). abc
5). compilation error
Solution :
option [5] is correct
Attempted :
option [5] is attempted 